version: '3.8'
services:
  frontend:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"